### ISSUE TITLE
The loading layout has failed to be created. java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by chonamdoo** [naver/android-pull-to-refresh#21]
안녕하세요 스튜디오 사용자인데요 
1097-1097/kr.co.withweb.ental E/LoadingLayoutFactory﹕ The loading layout has failed to be created.
java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at com.handmark.pulltorefresh.library.LoadingLayoutFactory.tryNewInstance(LoadingLayoutFactory.java:123)
at com.handmark.pulltorefresh.library.LoadingLayoutFactory.createLoadingLayout(LoadingLayoutFactory.java:105)
at com.handmark.pulltorefresh.library.PullToRefreshBase.createLoadingLayout(PullToRefreshBase.java:725)
at com.handmark.pulltorefresh.library.PullToRefreshBase.init(PullToRefreshBase.java:1423)
at com.handmark.pulltorefresh.library.PullToRefreshBase.(PullToRefreshBase.java:201)
at com.handmark.pulltorefresh.library.PullToRefreshAdapterViewBase.(PullToRefreshAdapterViewBase.java:88)
at com.handmark.pulltorefresh.library.PullToRefreshListView.(PullToRefreshListView.java:51)
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:600)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
at kr.co.withweb.ental.fragment.CategoryFragment.onCreateView(CategoryFragment.java:236)
이런 오류가 발생하네여 ㅠㅠ

**Comment by ncoolz** [comment]
Thanks for new posting. I'll wait for your sample project for tracing the issue. :)

**Comment by chonamdoo** [comment]
public class CategoryFragment extends BaseFragment implements PullToRefreshBase.OnRefreshListener, OnCategoryDataClickBtnListener, OnScrollListener {
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_list, null);

```
    listview = (PullToRefreshListView) view.findViewById(R.id.refresh_list);
    listview.setOnRefreshListener(this);
    listview.setOnScrollListener(this);
    actualList = (ListView) listview.getRefreshableView();
    actualList.addFooterView(footerLayout);
    actualList.setAdapter(adapter);
    actualList.removeFooterView(footerLayout);
    actualList.setDivider(null);
    setNoExist(menuId);
    return view;
}
```

**Comment by ncoolz** [comment]
Could you please give it as a "project"? A piece of code doesn't help to trace that issue and it doesn't happen to me lol.
I recommend you to create a new project and make it occurring the problem. Thank you.

**Comment by chonamdoo** [comment]
앗 해결했습니다 ㅠㅠ 신경쓰게 해서 죄송 ㅎㅎ
