### ISSUE TITLE
Add support to android studio preview

### ISSUE THREAD

**Issue by lightglitch** [naver/android-pull-to-refresh#8]
I get this:

```
The following classes could not be instantiated:
- com.handmark.pulltorefresh.library.PullToRefreshListView (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.NullPointerException   
 at android.content.res.BridgeResources.getXml(BridgeResources.java:548)   
 at com.handmark.pulltorefresh.configuration.xml.PullToRefreshXmlConfiguration.init(PullToRefreshXmlConfiguration.java:92)   
 at com.handmark.pulltorefresh.library.PullToRefreshBase.init(PullToRefreshBase.java:1358)   
 at com.handmark.pulltorefresh.library.PullToRefreshBase.<init>(PullToRefreshBase.java:201)   
 at com.handmark.pulltorefresh.library.PullToRefreshAdapterViewBase.<init>(PullToRefreshAdapterViewBase.java:84)   
 at com.handmark.pulltorefresh.library.PullToRefreshListView.<init>(PullToRefreshListView.java:50)   
 at java.lang.reflect.Constructor.newInstance(Constructor.java:526)   
 at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:755)   
 at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)   
 at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:758)   
 at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)   
 at android.view.LayoutInflater.inflate(LayoutInflater.java:492)  
 at android.view.LayoutInflater.inflate(LayoutInflater.java:373) Copy stack to clipboard 
```

**Comment by ncoolz** [comment]
I will check that and find the way to support it.

**Comment by ncoolz** [comment]
Now the library supports it in 3.2.2 version.
